export const FETCH_DATAHOTTREND = "FETCH_DATAHOTTREND";
export const FETCH_DATANEW = "FETCH_DATANEW";
export const FETCH_DATADETAIL = "FETCH_DATADETAIL";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_TOTALROW = "FETCH_TOTALROW";
export const FETCH_FILTERS = "FETCH_FILTERS";
export const FETCH_FILTERTOTALROW = "FETCH_FILTERTOTALROW";
